export type PartyType =
  | "DEVELOPER"
  | "GENERAL_CONTRACTOR"
  | "SITE_MANAGER"
  | "ARCHITECT"
  | "STRUCTURAL_ENGINEER"
  | "MEP_ENGINEER"
  | "SUBCONTRACTOR"
  | "SUPPLIER"
  | "LOGISTICS"
  | "FINANCE_CONTROLLER"
  | "QUALITY_INSPECTOR"
  | "AUTHORITY";

export type RaciRole = "RESPONSIBLE" | "ACCOUNTABLE" | "CONSULTED" | "INFORMED";

type PhaseRaci = Partial<Record<PartyType, RaciRole>>;

// Default RACI map per phase — overridable per project.
export const DEFAULT_RACI: Record<string, PhaseRaci> = {
  DESIGN: {
    DEVELOPER: "ACCOUNTABLE",
    ARCHITECT: "RESPONSIBLE",
    STRUCTURAL_ENGINEER: "CONSULTED",
    MEP_ENGINEER: "CONSULTED",
    GENERAL_CONTRACTOR: "CONSULTED",
    SITE_MANAGER: "INFORMED",
    FINANCE_CONTROLLER: "INFORMED",
    AUTHORITY: "INFORMED",
  },
  PERMITS: {
    DEVELOPER: "ACCOUNTABLE",
    ARCHITECT: "RESPONSIBLE",
    AUTHORITY: "RESPONSIBLE",
    GENERAL_CONTRACTOR: "INFORMED",
    FINANCE_CONTROLLER: "CONSULTED",
    SITE_MANAGER: "INFORMED",
  },
  PROCUREMENT: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    LOGISTICS: "RESPONSIBLE",
    SUPPLIER: "CONSULTED",
    FINANCE_CONTROLLER: "CONSULTED",
    SITE_MANAGER: "INFORMED",
    DEVELOPER: "INFORMED",
  },
  SITE_PREP: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    DEVELOPER: "INFORMED",
  },
  EARTHWORKS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    STRUCTURAL_ENGINEER: "CONSULTED",
    QUALITY_INSPECTOR: "CONSULTED",
    DEVELOPER: "INFORMED",
  },
  FOUNDATIONS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    STRUCTURAL_ENGINEER: "CONSULTED",
    QUALITY_INSPECTOR: "RESPONSIBLE",
    LOGISTICS: "CONSULTED",
    DEVELOPER: "INFORMED",
    FINANCE_CONTROLLER: "INFORMED",
  },
  STRUCTURE: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    STRUCTURAL_ENGINEER: "CONSULTED",
    QUALITY_INSPECTOR: "RESPONSIBLE",
    DEVELOPER: "INFORMED",
  },
  ENVELOPE: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    QUALITY_INSPECTOR: "CONSULTED",
  },
  ROOF: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    QUALITY_INSPECTOR: "CONSULTED",
  },
  FACADE: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    ARCHITECT: "CONSULTED",
    QUALITY_INSPECTOR: "CONSULTED",
  },
  WINDOWS_DOORS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    SUPPLIER: "CONSULTED",
  },
  MEP_ROUGH: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    MEP_ENGINEER: "CONSULTED",
    SUBCONTRACTOR: "RESPONSIBLE",
    SITE_MANAGER: "RESPONSIBLE",
    QUALITY_INSPECTOR: "CONSULTED",
  },
  PARTITIONS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
  },
  PLASTERING: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    QUALITY_INSPECTOR: "CONSULTED",
  },
  SCREED_FLOORS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
  },
  FINISHING: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
    ARCHITECT: "CONSULTED",
    QUALITY_INSPECTOR: "CONSULTED",
    DEVELOPER: "INFORMED",
  },
  EXTERNAL_WORKS: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    SITE_MANAGER: "RESPONSIBLE",
    SUBCONTRACTOR: "RESPONSIBLE",
  },
  INSPECTIONS: {
    QUALITY_INSPECTOR: "RESPONSIBLE",
    AUTHORITY: "ACCOUNTABLE",
    GENERAL_CONTRACTOR: "CONSULTED",
    SITE_MANAGER: "CONSULTED",
    DEVELOPER: "INFORMED",
  },
  COMMISSIONING: {
    GENERAL_CONTRACTOR: "ACCOUNTABLE",
    MEP_ENGINEER: "RESPONSIBLE",
    SUBCONTRACTOR: "CONSULTED",
    QUALITY_INSPECTOR: "CONSULTED",
    DEVELOPER: "INFORMED",
  },
  HANDOVER: {
    DEVELOPER: "ACCOUNTABLE",
    GENERAL_CONTRACTOR: "RESPONSIBLE",
    SITE_MANAGER: "CONSULTED",
    QUALITY_INSPECTOR: "CONSULTED",
    FINANCE_CONTROLLER: "INFORMED",
  },
};

export interface RaciSeed {
  partyType: PartyType;
  raciRole: RaciRole;
}

// Returns the default RACI assignments for a given phase.
export function raciForPhase(phase: string): RaciSeed[] {
  const map = DEFAULT_RACI[phase];
  if (!map) return [];
  return (Object.entries(map) as [PartyType, RaciRole][]).map(
    ([partyType, raciRole]) => ({ partyType, raciRole })
  );
}
